apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui
  namespace: {{ .Values.controller.namespace }}
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080


---
apiVersion: v1
kind: Service
metadata:
  name: jnkins-jnlp
  namespace: {{ .Values.controller.namespace }}
spec:
  selector:
    app: jenkins
  ports:
  - name: jnlp
    port: 50000
    targetPort: 50000
