apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui
  namespace: {{ .Values.controller.namespace }}
spec:
  selector:
    {{- include "jenkins.lables" . | nindent 4 }}
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: jnkins-jnlp
  namespace: {{ .Values.controller.namespace }}
spec:
  selector:
    {{- include "jenkins.lables" . | nindent 4  }}
  ports:
  - name: jnlp
    port: 50000
    targetPort: 50000
