apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.controller.StatefulsetName }}
  namespace: {{ .Values.controller.namespace }}
spec:
  selector:
    matchLabels:
      app: jenkins
      env: {{ .Values.controller.env }}
      version: 2.387
  serviceName: jenkins-ui
  replicas: {{ .Values.controller.replicas }}
  template:
    metadata:
      labels:
        app: jenkins
        env: {{ .Values.controller.env }}
        version: 2.387
    spec:
      securityContext:
            fsGroup: 1000 
            runAsUser: 1000
            runAsNonRoot: true
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 10
      containers:
      - name: jenkins
        {{- $img := .Values.controller.env  }}
        image: {{ .Values.controller.image }}:{{- if eq $img "dev"}}1.1 {{- else}}1.0 {{- end }}
        imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.controller.resources.requests.cpu }}
            memory: {{ .Values.controller.resources.requests.memory }}
          limits:
            cpu: {{ .Values.controller.resources.limits.cpu }}
            memory: {{ .Values.controller.resources.limits.memory }}
        ports:
        - containerPort: {{ .Values.controller.ports.containerPort1 }}
          name: {{ .Values.controller.ports.name1 }}
        - containerPort: {{ .Values.controller.ports.containerPort2 }}
          name: {{ .Values.controller.ports.name2 }}
        startupProbe:
          httpGet:
            path: '/login'
            port: 8080
          initialDelaySeconds: 90
          failureThreshold: 30  
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: "/login"
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe: 
          httpGet:
            path: "/login"
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
          - name: CASC_JENKINS_CONFIG
            value: /var/jenkins_home/casc_configs
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-config
          mountPath: /var/jenkins_home/casc_configs
      volumes:
      - name: jenkins-config
        configMap: 
          name: jcasc-config
  volumeClaimTemplates:
  - metadata:
      name: jenkins-home
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi



