apiVersion: v1
kind: ConfigMap
metadata:
  name: jcasc-config
  labels:
  {{- include "jenkins.lables" . | nindent 4  }}
data:
  jenkins-casc.yaml: |
    jenkins:
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      securityRealm:
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "admin"
            name: "Dheeraj"
            password: "admin"
      numExecutors: 0
      clouds:
      - kubernetes:
          containerCapStr: "10"
          defaultsProviderTemplate: ""
          connectTimeout: "5"
          readTimeout: "15"
          webSocket: true
          jenkinsUrl: "http://jenkins-ui.default.svc.cluster.local:8080"
          maxRequestsPerHostStr: "32"
          name: "kubernetes"
          namespace: "default"
          serverUrl: "https://kubernetes.default"
          podLabels:
          - key: "jenkins"
            value: "agent"
          templates:
            - name: "default"
              namespace: "default"
              containers:
              - name: "jnlp"
                alwaysPullImage: false
                args: "^${computer.jnlpmac} ^${computer.name}"
                command: 
                envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://jenkins-ui.default.svc.cluster.local:8080/"
                image: "jenkins/inbound-agent:3107.v665000b_51092-15"
                privileged: "false"
                ttyEnabled: false
                workingDir: /home/jenkins/agent
              idleMinutes: 0
              instanceCap: 2147483647
              label: "jenkins-jenkins-agent "
              nodeUsageMode: "NORMAL"
              podRetention: Never
              showRawYaml: true
              slaveConnectTimeoutStr: "100"
              yamlMergeStrategy: override
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: true


