apiVersion: v1
kind: ConfigMap
metadata:
  name: jcasc-config
  labels:
  {{- include "jenkins.lables" . | nindent 4  }}
data:
  jenkins-casc.yaml: |
    jenkins:
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      securityRealm:
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "admin"
            name: "Dheeraj"
            password: "admin"
      numExecutors: 0
      clouds:
      - kubernetes:
          containerCapStr: "10"
          defaultsProviderTemplate: ""
          connectTimeout: "5"
          readTimeout: "15"
          webSocket: {{ .Values.agent.webSocket }}
          jenkinsUrl: "http://jenkins-ui.{{ .Values.controller.namespace }}.svc.cluster.local:{{ .Values.controller.service.HttpPort }}"
          maxRequestsPerHostStr: "32"
          name: "kubernetes"
          namespace: "{{ .Values.agent.namespace }}"
          serverUrl: "https://kubernetes.default"
          podLabels:
          - key: "jenkins"
            value: "agent"
          templates:
            - name: "default"
              namespace: "default"
              containers:
              - name: "jnlp"
                alwaysPullImage: {{ .Values.agent.pullImage }}
                args: "^${computer.jnlpmac} ^${computer.name}"
                command: 
                envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://jenkins-ui.{{ .Values.controller.namespace }}.svc.cluster.local:{{ .Values.controller.service.HttpPort }}/"
                image: "{{ .Values.agent.image }}:{{ .Values.agent.tag }}"
                privileged: "false"
                ttyEnabled: false
                workingDir: {{ .Values.agent.workingDir }}
              idleMinutes: 0
              label: "jenkins-agent "
              nodeUsageMode: "NORMAL"
              podRetention: Never
              showRawYaml: true
              slaveConnectTimeoutStr: "100"
              yamlMergeStrategy: override
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: true

          


