apiVersion: v1
kind: ConfigMap
metadata:
  name: jcasc-config
  labels:
  {{- include "jenkins.lables" . | nindent 4  }}
data:
  jenkins-casc.yaml: |
    jenkins:
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      securityRealm:
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "admin"
            name: "Dheeraj"
            password: "admin"
      numExecutors: 0


