version: '3.9'
services:
  docker:
    image: docker:dind
    privileged: true
    command: --storage-driver=overlay2
    networks:
      jenkins:
        aliases:
          - docker 
    ports:
      - 2376:2376
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    container_name: jenkins-docker
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client

  jenkins:
    build:
      context: .
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    container_name: jenkins-lts
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
  sonar:
    image: sonarqube:lts-community
    networks:
      - jenkins
    ports:
      - 9000:9000
    container_name: sonarqube
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
volumes:
  jenkins_home: {}
  jenkins-docker-certs: {}
  sonar_data: {}
  sonar_logs: {}
networks:
  jenkins: