controller:
  namespace: default

  image: dheerajlearningdocker/jenkins
  tag: 1.0
  imagePullPolicy: Always
  replicas: 1
  env: ppe

  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 2Gi

  ports:
    containerPort1 : 8080
    name1 : http
    containerPort2: 50000
    name2: jnlp

  
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true

  startupProbe:
    httpGet:
      path: '/login'
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 30  
    periodSeconds: 10
    timeoutSeconds: 5
  livenessProbe:
    httpGet:
      path: "/login"
      port: 8080
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  readinessProbe: 
    httpGet:
      path: "/login"
      port: 8080
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
 
  persistance:
    name: jenkins-home
    accessModes: ReadWriteOnce
    storage: 8Gi

  