controller:
  namespace: default
  deploymentName: jenkins

  image: dheerajlearningdocker/jenkins
  tag: 1.0
  imagePullPolicy: Always
  replicas: 1

  serviceAccountName: jenkins

  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 2Gi

  ports:
    - containerPort: 8080
      name: http
    - containerPort: 50000
      name: jnlp

  
  startupProbe:
    httpGet:
      path: '/login'
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 30  
    periodSeconds: 10
    timeoutSeconds: 5
  livenessProbe:
    httpGet:
      path: "/login"
      port: 8080
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  readinessProbe: 
    httpGet:
      path: "/login"
      port: 8080
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
 
  persistance:
    name: jenkins-home
    accessModes: ReadWriteOnce
    storage: 8Gi

  